Feature/zoom events page
torchbox/torchbox-frontend pull request #127
Opened 2020-09-24 08:08 UTC by NathHorrigan

This PR adds the FE for the events page

2020-09-24 09:00 UTC, kaedroho requested changes

2020-09-25 13:40 UTC, NathHorrigan commented on src/templates/case-study/case-study.js
> +      className={styles.pageTitle}
Editor auto change, Soz!

2020-09-25 14:06 UTC, NathHorrigan commented on src/templates/blog-post/index.js
> +        author={authorDetails(page.authors)[0]}
This is related, It's because that utility function has been changed for use on the events page :)

2020-09-25 14:07 UTC, NathHorrigan commented on src/templates/event/event.js
> +          {/* Show error messafe */}
Fixed.

2020-09-25 14:08 UTC, NathHorrigan commented on src/templates/event/event.js
> +    const url = `http://localhost:8000/api/events/${event?.eventType}/${event?.id}/register/`
Good catch!

2020-09-25 14:21 UTC, NathHorrigan commented on src/templates/event/event.js
> +          <span>{(event.eventType == "meeting" || event.eventType == "webinar") && "Online / Zoom" }</span>
Good idea!

2021-05-12 10:11 UTC, closed without merging